supplier:
  gstin: "27ABCDE1234F1Z5"
  legal_name: "MEGARUSHER Technologies"
  address: "Mumbai, Maharashtra"
  state_code: "27"
  composition: false

customer:
  name: "Default Client"
  gstin: "29XYZAB1234C1Z2"
  address: "Bangalore, Karnataka"
  state_code: "29"

defaults:
  quantity: 1
  unit_price: 10000
  tax_rate: 18
